[32] Allow modules to show warnings
Exein-io/pulsar pull request #203
Opened 2023-09-15 22:01 UTC by axenna

Allow modules to show warnings

## Implementation
Uses ctx to allow adding a warning to running status

## I have 

- [ ] run `cargo fmt`;
- [ ] run `cargo clippy`;
- [ ] run `cargo test`and all tests pass;
- [ ] linked to the originating issue (if applicable).

resolves #32

2023-09-18 14:43 UTC, banditopazzo requested changes
`add_warning` should be inside `ModuleSender` instead of `PulsarDaemonHandle` .

errors and warning handling happens inside the `ModuleManager` leading to an update of the module status.

you can modify `error_sender` inside `ModuleSender` :
```rust 
    pub(crate) error_sender: ErrorSender,
```
renaming it for example to `signal_sender` and using a channel not only for errors. in the channel you can send a new `enum` made with an error and a warning variants

2023-09-18 14:43 UTC, banditopazzo commented on crates/pulsar-core/src/pdk/daemon.rs
> +    Running(Option<String>),
it's better to use a `Vec<String>` to capture multiple warnings

2023-09-18 16:46 UTC, axenna commented
Yeah that makes way more sense, sorry!

2023-09-19 14:17 UTC, banditopazzo approved these changes
lgtm

2023-09-19 14:17 UTC, merged