Test suite refactor [WIP]
Exein-io/pulsar pull request #25
Opened 2022-07-15 14:57 UTC by MatteoNardi

This PR is a tentative refactor of the test suite.
Tests are split in a different binary, which can be invoked with sudo by using a xtask.

Fixes https://github.com/Exein-io/pulsar/issues/3

2022-07-28 14:58 UTC, MatteoNardi commented
All the test were ported to the new system. I'll work on documentation and general cleanup, than it will be ready for review.

2022-07-29 13:14 UTC, MatteoNardi commented
This PR is now ready for review.

- I've split the test suite in a different binary. See [README](https://github.com/Exein-io/pulsar/tree/test-suite/test-suite).
- I've added xtasks for every pulsar binary which need to be run as sudo. [See README](https://github.com/Exein-io/pulsar/tree/test-suite/xtask)
  - I've made `probe` a binary to make it more coherent with the others.
- `cargo test` doesn't require sudo anymore. I've re-enabled `validatron` tests.
- All documentation references in the repository should have been updated.

Some notes:

- I've decided to get rid of [inventory](https://github.com/dtolnay/inventory) for tests collection as I don't think the added value justified the added complexity. Every module has a test entrypoint which must be listed in the `test-suite` binary.

2022-08-22 13:26 UTC, banditopazzo requested changes

2022-08-23 06:46 UTC, MatteoNardi commented on bpf-common/src/test_runner.rs
> +}
The derive implementation doesn't support generics

2022-08-23 06:51 UTC, MatteoNardi commented
I've rebased to main and added https://github.com/Exein-io/pulsar/pull/25/commits/2b3e58454b91f689329490850a2b83112f5c13e3

2022-09-01 11:06 UTC, banditopazzo approved these changes

2022-09-01 11:06 UTC, merged