feat: Include list of image layer directories in `ContainerInfo`
exein-io/pulsar pull request #294
Opened 2024-06-17 07:17 UTC by vadorovsky

For each container, try to retrieve information about image layers paths (from the host filesystem's perspective) and include them in `ContainerInfo`.

2024-06-18 11:49 UTC, banditopazzo requested changes
Please handle the `unwrap`s

2024-07-02 15:38 UTC, banditopazzo requested changes
In general it seems fine, but there is no support for podman

2024-07-07 20:42 UTC, vadorovsky commented on crates/bpf-common/src/containers/mod.rs
> +            // TODO(vadorovsky): Parse layer information in Podman.
Added in #309 309

2024-09-07 04:51 UTC, vadorovsky commented on crates/bpf-common/src/containers/mod.rs
> +            layers: Vec::new(),
I must've done a wrong `git push -f`. I restored them now, sorry.

2024-09-18 10:38 UTC, banditopazzo approved these changes

2024-09-18 13:10 UTC, merged