feat: Detect image layer directory for Podman
exein-io/pulsar pull request #309
Opened 2024-07-07 17:46 UTC by vadorovsky

Use libpod's image store and layer store to determine image layer directories on the host for Podman.

2024-07-11 17:11 UTC, banditopazzo requested changes
A very small detail in the code and a question.

So basically the `podman_layers` function returns you the list of all `.../diff`, `.../merged`, `.../work` directories involved?

2024-07-29 06:27 UTC, vadorovsky commented
>So basically the podman_layers function returns you the list of all .../diff, .../merged, .../work directories involved, correct?

Yes, exactly.

2024-07-29 06:52 UTC, vadorovsky commented on crates/bpf-common/src/containers/mod.rs
> +                id: image_id.clone(),
Done, sorry for late reaction

2024-07-30 12:54 UTC, banditopazzo approved these changes

2024-08-05 10:12 UTC, merged