feat(filtering): validate images configuration
Exein-io/pulsar pull request #8
Opened 2022-06-28 15:15 UTC by MatteoNardi

The filtering policy would just log an error and ignore the configured
field before this change. Since an error in process filtering causes all
events to be lost, we've decided to fail the module, making the error
more visible.

# Pull Request Title

_Short introduction explaining the motivation and reasoning behind the pull request._

## Implementation (Optional)

_Feel free to include design and implementation for external review outside of the code changes._

## I have 

- [x] run `cargo fmt`;
- [x] run `cargo clippy`;
- [x] run `cargo test`and all tests pass;
- [ ] linked to the originating issue (if applicable).

2022-06-28 15:39 UTC, MatteoNardi commented on modules/process-monitor/src/filtering/config.rs
> +    pub(crate) image: Vec<u8>,
To convey the fact it was ASCII validated. 
Do you think `String` would be better? I'm neutral on this, as long as we do validation ad config reading time.

2022-07-05 14:37 UTC, banditopazzo requested changes

2022-07-05 14:50 UTC, MatteoNardi commented on modules/process-monitor/src/filtering/maps.rs
>              image.0.clone_from_slice(&src[..]);
It's still needed.
`config::Image` contains a `Vec<u8>`, we know its length is **up to** MAX_IMAGE_LEN.
The `maps::Image` defined at line 109 must copy from a src of exactly MAX_IMAGE_LEN, or `clone_from_slice` will panic.

I don't like the fact we have two `Image` newtypes in the same crate. I could modify `config` to use the `maps::Image` one. Or I could rename `config::Image` to `ImagePod`. What do you think?

2022-07-08 13:24 UTC, banditopazzo approved these changes

2022-07-08 13:34 UTC, merged